Warehouse/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;
using System.Collections.Generic;
using Warehouse.Models;
using Warehouse.Service.IService;
using Warehouse.Utility;

namespace Warehouse.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemService itemService;
        public ItemController(IItemService itemService)
        {
            this.itemService = itemService;
        }
        public async Task<IActionResult> ItemIndex()
        {
            List<ItemDto> listItem = new List<ItemDto>();

            ResponseDto response = await itemService.GetAllItemsAsync();

            if (response != null && response.IsSuccess)
            {
                listItem = JsonConvert.DeserializeObject<List<ItemDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.ErrorMessage;
            }
            return View(listItem);
        }
		public async Task<IActionResult> InsertUpdateItem(int id=0)
		{
			var statusList = new List<SelectListItem>()
			{
				new SelectListItem{Text=SD.StatusActive,Value="1"},
				new SelectListItem{Text=SD.StatusNonActive,Value="0"},
			};
			ViewBag.statusList = statusList;
			ViewBag.statusItem = "Create";
			ItemDto itemDto = new ItemDto();
			if (id!=0)
			{
				ResponseDto? response = await itemService.GetItemByIdAsync(id);

				if (response != null && response.IsSuccess)
				{
					ViewBag.statusItem = "Update";
					ItemDto? model = JsonConvert.DeserializeObject<ItemDto>(Convert.ToString(response.Result));
					return View(model);
				}
				else
				{
					TempData["error"] = response?.ErrorMessage;
				}
			}

			return View(itemDto);
		}

		[HttpPost]
		public async Task<IActionResult> ItemDelete(int id)
		{
			ResponseDto? response = await itemService.DeleteItemAsync(id);

			if (response != null && response.IsSuccess)
			{
				TempData["success"] = "item deleted successfully";
				return RedirectToAction("ItemIndex");
			}
			else
			{
				TempData["error"] = response?.ErrorMessage;
			}
			return RedirectToAction("ItemIndex");
		}

		[HttpPost]
		public async Task<IActionResult> InsertUpdateItem(ItemDto model)
        {
            model.LastUpdated = DateTime.Now;
            if (ModelState.IsValid)
			{
				ResponseDto? response = await itemService.InsertUpdateItemsAsync(model);

				if (response != null && response.IsSuccess)
				{
					TempData["success"] = "Item created successfully";
					return RedirectToAction("ItemIndex");
				}
				else
				{
					TempData["error"] = response?.ErrorMessage;
				}
			}
			var statusList = new List<SelectListItem>()
			{
				new SelectListItem{Text=SD.StatusActive,Value="1"},
				new SelectListItem{Text=SD.StatusNonActive,Value="0"},
			};

			ViewBag.statusList = statusList;
			return View(model);
		}
	}
}

Warehouse/Controllers/TransactionItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Warehouse.Models;
using Warehouse.Service.IService;
using Warehouse.Utility;

namespace Warehouse.Controllers
{
    public class TransactionItemController : Controller
    {
        private readonly IItemService itemService;
        private readonly ITransactionItemService transactionItemService;
        private readonly IHttpContextAccessor httpContextAccessor;
        public TransactionItemController(IItemService itemService, ITransactionItemService transactionItemService, IHttpContextAccessor httpContextAccessor)
        {
            this.itemService = itemService;
            this.transactionItemService = transactionItemService;
            this.httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult> TransactionIndex()
        {
            List<ItemDto> listItem = new List<ItemDto>();

            ResponseDto response = await itemService.GetAllItemsAsync();

            if (response != null && response.IsSuccess)
            {
                listItem = JsonConvert.DeserializeObject<List<ItemDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.ErrorMessage;
            }
            return View(listItem);
        }

		public async Task<IActionResult> Order(int id = 0)
		{
			OrderItem orderItem = new OrderItem();
			if (id != 0)
			{
				ResponseDto? response = await itemService.GetItemByIdAsync(id);

				if (response != null && response.IsSuccess)
				{
					ItemDto? model = JsonConvert.DeserializeObject<ItemDto>(Convert.ToString(response.Result));
                    orderItem.ItemID = model.ItemID;
                    orderItem.ItemName = model.ItemName;
                    orderItem.RemainingItemAmount = model.ItemAmount;
                    return View(orderItem);
				}
				else
				{
					TempData["error"] = response?.ErrorMessage;
				}
			}

			return View(orderItem);
		}

        public async Task<IActionResult> OrderList()
        {
            string? status = httpContextAccessor.HttpContext.Session.GetString("status");
            string? userID = httpContextAccessor.HttpContext.Session.GetString("ID");
            List<TransactionListItemDto> listTransaction = new List<TransactionListItemDto>();
            if (!string.IsNullOrEmpty(userID))
            {
                ResponseDto response = await transactionItemService.GetAllTransactionItemsAsync();
                listTransaction = JsonConvert.DeserializeObject<List<TransactionListItemDto>>(Convert.ToString(response.Result));
                if (status.Equals("1")) 
                {
                    listTransaction = listTransaction.Where(x => x.UserID.ToString().Equals(userID)).ToList();
                }
            }

            return View(listTransaction);
        }

        [HttpPost]
        public async Task<IActionResult> Order(OrderItem model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TransactionItemDto transactionItemDto = new TransactionItemDto
                    {
                        TransactionItemID = 0,
                        ItemID = model.ItemID,
                        ItemAmount = model.ItemAmount,
                        ItemPrice = model.ItemPrice,
                        UserID = model.UserID,
                        RecipientName = model.RecipientName,
                        TransactionDate = DateTime.Now
                    };
                    ResponseDto? response = await transactionItemService.InsertTransactionItemAsync(transactionItemDto);

                    if (response != null && response.IsSuccess)
                    {
                        TempData["success"] = "Item created successfully";
                        return RedirectToAction("TransactionIndex");
                    }
                    else
                    {
                        TempData["error"] = response?.ErrorMessage;
                    }
                }
            }
            catch(Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return View(model);
        }
    }
}

Warehouse/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Xml.Linq;
using Warehouse.Models;
using Warehouse.Service.IService;
using Warehouse.Utility;

namespace Warehouse.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IHttpContextAccessor httpContextAccessor;
        public UserController(IUserService userService, IHttpContextAccessor httpContextAccessor)
        {
            this.userService = userService;
            this.httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value="0"},
                new SelectListItem{Text=SD.RoleStaff,Value="1"},
            };

            ViewBag.RoleList = roleList;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequest login)
        {
            try
            {
                UserDto user = new UserDto
                {
                    ID = 0,
                    Email = login.Email,
                    Password = login.Password,
                    Name = string.Empty,
                    PhoneNumber = string.Empty,
                    Status = 0
                };
                ResponseDto result = await userService.LoginAsync(user);

                if (result != null && result.IsSuccess)
                {
                    user = JsonConvert.DeserializeObject<UserDto>(Convert.ToString(result.Result));
                    TempData["success"] = "Login Successful";
                    httpContextAccessor.HttpContext.Session.SetString("Name", user.Name);
                    httpContextAccessor.HttpContext.Session.SetString("ID", user.ID.ToString());
                    httpContextAccessor.HttpContext.Session.SetString("status", user.Status.ToString());

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["error"] = "Login Failed";
                }

            }
            catch(Exception ex)
            {
                TempData["error"] = ex;
            }
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Register(UserDto user)
        {
            try
            {
                ResponseDto result = await userService.RegisterAsync(user);

                if (result != null && result.IsSuccess)
                {
                    TempData["success"] = "Registration Successful";
                    httpContextAccessor.HttpContext.Session.SetString("Name", user.Name);
                    httpContextAccessor.HttpContext.Session.SetString("ID", user.ID.ToString());
                    httpContextAccessor.HttpContext.Session.SetString("status", user.Status.ToString());

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["error"] = result.ErrorMessage;
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex;
            }
            

            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value="0"},
                new SelectListItem{Text=SD.RoleStaff,Value="1"},
            };

            ViewBag.RoleList = roleList;
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            httpContextAccessor.HttpContext.Session.SetString("Name", "");
            httpContextAccessor.HttpContext.Session.SetString("ID", "");
            httpContextAccessor.HttpContext.Session.SetString("status", "");
            return RedirectToAction("Index", "Home");
        }
    }
}

Warehouse/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor httpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Warehouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Warehouse.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Warehouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav pull-right">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">

                            @if (httpContextAccessor.HttpContext.Session.GetString("status") != null && httpContextAccessor.HttpContext.Session.GetString("status").Equals("0"))
                            {
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li> <a class="dropdown-item" asp-controller="Item" asp-action="ItemIndex">Item Management</a></li>
                                    <li> <a class="dropdown-item" asp-controller="TransactionItem" asp-action="OrderList">List Order Item</a></li>
                                </ul>
                            }
                            else if (httpContextAccessor.HttpContext.Session.GetString("status") != null && httpContextAccessor.HttpContext.Session.GetString("status").Equals("1"))
                            {

                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Manage Order
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li> <a class="dropdown-item" asp-controller="TransactionItem" asp-action="TransactionIndex">Order Item</a></li>
                                    <li> <a class="dropdown-item" asp-controller="TransactionItem" asp-action="OrderList">List Order Item</a></li>
                                </ul>
                            }
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (httpContextAccessor.HttpContext.Session.GetString("ID") == null || httpContextAccessor.HttpContext.Session.GetString("ID").Equals(""))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#">Hello @httpContextAccessor.HttpContext.Session.GetString("Name")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Warehouse - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Warehouse/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}